language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # GraphViz
  - sudo apt-get install -qq graphviz
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh

services:
  - xvfb

script: 
  # Build and run tests
  - make console_test
  - ./Console/CityOfThievesConsoleTest
  - make console
  - make desktop
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Codecov
  - ./get_code_cov.sh &> /dev/null
  - codecov &> /dev/null
  # OCLint
  - ./do_oclint.sh || true

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

