language: cpp
compiler: gcc
dist: trusty

before_install:
  # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # GraphViz
  - sudo apt-get install -qq graphviz
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # libnds
  - sudo ./build_libnds_64

addons:
  apt: 
    packages: libboost-all-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Build and run tests
  - ./build_files
  - ./build_console_test
  - ./Console/CityOfThievesConsoleTest
  - ./build_console
  - ./build_desktop
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Codecov
  - ./get_code_cov
  - codecov
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)


